### ISSUE TITLE
讨论/建议

### ISSUE THREAD

**Issue by honue** [HankunYu/MoviePilot-Plugins#1]
有没有想过把bangumi插件拆分一下，
1.同步MoviePilot的观看记录到 Bangumi 收藏中。
2. 自动订阅/下载 Bangumi 收藏的"想看"条目。 
3. 更改本地动漫 NFO文件评分为Bangumi评分。 更改订阅页面的评分为Bangumi评分。
觉得三个合一起太杂了，1 3可以单独拿出来做成两个插件 
2的话去rsshub新增一个路由，rss链接可以丢给榜单订阅那个插件，榜单订阅都是直接读title订阅下载。

**Comment by honue** [comment]
对1挺感兴趣的，但是这三个功能揉在一起感觉好杂乱，有的功能不需要。。

**Comment by honue** [comment]
[RssHub 用户想看](https://github.com/DIYgod/RSSHub/pull/13922#issuecomment-1833199258)

**Comment by HankunYu** [comment]
@honue 暂时不考虑拆分插件，感觉还是做成开关的方式比较好。不过会把不需要的功能相关内容隐藏。但是这里有个问题是vuetify的一些组件比如分页Tabs之类的在插件页面不起作用...没法在脚本里声明v-model的值

至于RSS倒是一个新思路，会整合进去替代用api读取用户想看

**Comment by honue** [comment]
全写一起感觉好复杂…

**Comment by HankunYu** [comment]
本来就打算写个同步媒体库到bangumi的插件，写着写着发现多加个功能也就多几行代码。。。
不拆的还一点就是这些功能的代码都是通的，不确定mp会不会下载没有安装的插件的脚本，不然拆了的话要么这些方法要在每个脚本里都复写一遍。。。

**Comment by honue** [comment]
mp不会下载没有安装的插件，页面的问题我也遇到了，select的optional不能和text文本框bind 有的时候想隐藏文本框，实现不了。
