### ISSUE TITLE
插件界面为空白

### ISSUE THREAD

**Issue by LoSiTeE** [HankunYu/MoviePilot-Plugins#2]
![ULGEL1WYX7Z9OAC}K$OYPHA](https://github.com/HankunYu/MoviePilot-Plugins/assets/125968595/0ab951bf-669d-479b-af26-4492fa780ee5)
![WR41K95Z13N`6A9Z42S%`37](https://github.com/HankunYu/MoviePilot-Plugins/assets/125968595/b71f5f17-8336-45a1-a2e6-21792f9332f3)

**Comment by HankunYu** [comment]
看着像脚本版本没拉对？重启一下容器重拉脚本试试

**Comment by lux032** [comment]
bangumi插件同样为空白 目前已经是最新版本的mp了

**Comment by HankunYu** [comment]
> bangumi插件同样为空白 目前已经是最新版本的mp了

新版本mp改了点关于数据库的代码，我这边需要更新适配一下。今天会修好

**Comment by HankunYu** [comment]
这个bug已经修复，可以试试看更新到新版本
