### ISSUE TITLE
discord配置可以增加http代理吗

### ISSUE THREAD

**Issue by ZACKLZ** [HankunYu/MoviePilot-Plugins#4]
discord配置可以增加http代理吗？最近不知道怎么的，收不到推送了
![image](https://github.com/HankunYu/MoviePilot-Plugins/assets/82872715/2cfd73d6-4d77-4411-a145-c695e476d12d)

**Comment by HankunYu** [comment]
啊抱歉最近这两天想给这个插件加个discord bot还没做完，可能破坏了原来的逻辑。我尽快修好，好了再通知你声

**Comment by HankunYu** [comment]
顺便能发下这个报错前后log看下么

**Comment by HankunYu** [comment]
还有收不到的问题么？
