### ISSUE TITLE
BANGUMI插件只更新了集的评分，不更新番剧评分

### ISSUE THREAD

**Issue by jotaro167** [HankunYu/MoviePilot-Plugins#5]
![Uploading 6a96153f1a88195f50734d691d342c4a.png…]()

**Comment by HankunYu** [comment]
兄弟你图片上传失败了，能再传一次么

**Comment by jotaro167** [comment]
![{FD6A27D8-2CFD-44a3-AB05-142D2A18A215}](https://github.com/HankunYu/MoviePilot-Plugins/assets/127292049/db123952-8210-4f4b-82c7-0d24d7834b54)
不好意思

**Comment by jotaro167** [comment]
![S40225-10044412](https://github.com/HankunYu/MoviePilot-Plugins/assets/127292049/14b08c87-8db0-49a8-ab9a-73874db919dd)
![S40225-10044715](https://github.com/HankunYu/MoviePilot-Plugins/assets/127292049/cdbb2f1d-ee5b-4d00-9468-d1b867aaaebb)
现在emby效果是这样的

**Comment by HankunYu** [comment]
感谢，
已修复，但是好像不支持对各季的评分？多季只会有一个评分。
