### ISSUE TITLE
bangumi插件对混合媒体库不扫描

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [HankunYu/MoviePilot-Plugins#6]
我的动漫库是混合媒体库插件直接略过不扫描

**Comment by HankunYu** [comment]
> 我的动漫库是混合媒体库插件直接略过不扫描

可能是最近媒体库目录更新导致的 我尽快修复

**Comment by HankunYu** [comment]
测试了一下好像没问题？有开二级分类吗

**Comment by SchrodingerBarbatos** [comment]
> 测试了一下好像没问题？有开二级分类吗

开了，但是我的电影和电视剧库也是二级分类不是混合分类就都被扫了，然后提示媒体库扫描完成，因为我只有动漫是混合媒体库，所以觉得是不是·这个原因

**Comment by SchrodingerBarbatos** [comment]
> 测试了一下好像没问题？有开二级分类吗

另外请问一下这个媒体库路径是对应mp的映射路径吧？

**Comment by HankunYu** [comment]
不需要设定路径，是直接读取数据库中的条目做识别。路径只是为了更改已存在的nfo文件。

**Comment by SchrodingerBarbatos** [comment]
> 不需要设定路径，是直接读取数据库中的条目做识别。路径只是为了更改已存在的nfo文件。

我理解设置路径是为了修改已入库的nfo，但是我去除路径也不会扫描混合内容的媒体库

**Comment by SchrodingerBarbatos** [comment]
> 不需要设定路径，是直接读取数据库中的条目做识别。路径只是为了更改已存在的nfo文件。

mp自己的媒体库同步插件也不会同步混合内容的媒体库不知道是不是emby的api问题

**Comment by HankunYu** [comment]
那应该是这个问题，我是直接调用mp的数据库。数据库内不存在的就不会被扫描到……可以考虑去mp那提个issue

**Comment by SchrodingerBarbatos** [comment]
> 那应该是这个问题，我是直接调用mp的数据库。数据库内不存在的就不会被扫描到……可以考虑去mp那提个issue

好的谢谢
