### ISSUE TITLE
大佬,什么时候结束爱优腾还有b站的字幕啊

### ISSUE THREAD

**Issue by lifujie25** [HankunYu/MoviePilot-Plugins#7]
大佬,什么时候结束爱优腾还有b站的字幕啊

**Comment by HankunYu** [comment]
b站弹幕默认开启的 基于弹弹play的api （当然也没打算关闭
爱优腾还没计划支持。。。除非找到类似弹弹play这种已经根据hash匹配好资源的api

**Comment by lifujie25** [comment]
这里有 2 个项目，好像都有支持爱优腾，就不知道有没有 api
https://github.com/cxfksword/jellyfin-plugin-danmu
https://github.com/fengymi/emby-plugin-danmu

**Comment by HankunYu** [comment]
简单看了一眼 基本都要自己重新实现。工作量有点大近期估计是没时间搞了

**Comment by lifujie25** [comment]
好吧，感谢大佬，一直想找 mp 有没有弹幕，今天早上刷一下，有了，不过只有弹弹
